[project]
name = "cell-size-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "polars>=1.35.2",
    "pyqt6==6.9",
    "ruff>=0.14.5",
]
